import type { BrandModelOption, CarBrand } from "./types";

type ModelEntry = [string, string, string];

function models(brandId: string, entries: ModelEntry[]): Omit<BrandModelOption, "variants">[] {
  return entries.map(([id, name, price]) => ({
    id: `${brandId}-${id}`,
    name,
    price,
    brandId,
  }));
}

const DEFAULT_VARIANTS = ["Base", "Mid", "Top"];

/** Trim / variant names keyed by catalog model id */
const MODEL_VARIANTS: Record<string, string[]> = {
  "maruti-swift": ["LXi", "VXi", "VXi+", "ZXi", "ZXi+"],
  "maruti-baleno": ["Sigma", "Delta", "Zeta", "Alpha"],
  "maruti-brezza": ["LXi", "VXi", "ZXi", "ZXi+"],
  "maruti-grand-vitara": ["Sigma", "Delta", "Zeta", "Alpha", "Alpha+"],
  "maruti-fronx": ["Sigma", "Delta", "Zeta", "Alpha", "Turbo"],
  "hyundai-creta": ["E", "EX", "S", "S+", "SX", "SX(O)"],
  "hyundai-venue": ["E", "S", "S+", "SX", "SX(O)"],
  "hyundai-verna": ["EX", "S", "SX", "SX(O)"],
  "tata-nexon": ["Smart", "Smart+", "Creative", "Fearless", "Fearless+"],
  "tata-nexon-ev": ["Creative", "Fearless", "Fearless+", "Empowered"],
  "tata-punch": ["Pure", "Adventure", "Accomplished", "Creative"],
  "tata-harrier": ["Smart", "Pure", "Adventure", "Adventure+", "Fearless+"],
  "tata-harrier-ev": ["Adventure", "Empowered", "Empowered+ QWD"],
  "tata-safari": ["Smart", "Pure", "Adventure", "Adventure+", "Accomplished"],
  "tata-sierra": ["Pure", "Adventure", "Accomplished"],
  "tata-curvv": ["Creative", "Accomplished", "Empowered"],
  "tata-curvv-ev": ["Creative", "Accomplished", "Empowered+"],
  "mahindra-xuv700": ["MX", "AX3", "AX5", "AX7", "AX7 L"],
  "mahindra-scorpio-n": ["Z2", "Z4", "Z6", "Z8", "Z8 L"],
  "mahindra-thar": ["LX", "AX", "AX Opt", "AX Hard Top"],
  "kia-seltos": ["HTE", "HTK", "HTK+", "HTX", "HTX+", "GTX+", "X-Line"],
  "kia-sonet": ["HTE", "HTK", "HTK+", "HTX", "HTX+", "GTX+", "X-Line"],
  "toyota-innova-hycross": ["G", "GX", "VX", "ZX", "ZX(O)"],
  "toyota-fortuner": ["4x2 MT", "4x2 AT", "4x4 AT", "Legender"],
  "mg-hector": ["Style", "Super", "Smart", "Sharp", "Savvy Pro"],
  "mg-astor": ["Style", "Super", "Smart", "Sharp"],
  "honda-city": ["SV", "V", "VX", "ZX"],
  "vw-virtus": ["Comfortline", "Highline", "Topline", "GT Plus"],
  "vw-taigun": ["Comfortline", "Highline", "Topline", "GT Plus"],
  "vw-tiguan": ["Elegance", "Sportline", "R-Line"],
  "skoda-kushaq": ["Active", "Ambition", "Style", "Monte Carlo"],
  "skoda-slavia": ["Active", "Ambition", "Style", "Monte Carlo"],
  "skoda-octavia": ["Style", "Prestige", "Laurin & Klement"],
  "bmw-3-series": ["Sport", "M Sport", "M340i"],
  "bmw-x1": ["xDrive20d", "sDrive20i", "M Sport"],
  "bmw-x5": ["xDrive40i", "xDrive30d", "M Sport"],
  "mercedes-c-class": ["Progressive", "Avantgarde", "AMG Line"],
  "mercedes-e-class": ["Avantgarde", "Exclusive", "AMG Line"],
  "audi-a4": ["Premium", "Premium Plus", "Technology"],
  "audi-q5": ["Premium Plus", "Technology", "S line"],
  "jeep-compass": ["Sport", "Longitude", "Limited", "Model S"],
  "renault-kiger": ["RXE", "RXL", "RXT", "RXT(O)"],
};

function withVariants(model: Omit<BrandModelOption, "variants">): BrandModelOption {
  return {
    ...model,
    variants: MODEL_VARIANTS[model.id] ?? DEFAULT_VARIANTS,
  };
}

export const INDIA_CAR_BRANDS: CarBrand[] = [
  { id: "maruti", name: "Maruti Suzuki" },
  { id: "hyundai", name: "Hyundai" },
  { id: "tata", name: "Tata Motors" },
  { id: "mahindra", name: "Mahindra" },
  { id: "kia", name: "Kia" },
  { id: "toyota", name: "Toyota" },
  { id: "mg", name: "MG Motor" },
  { id: "honda", name: "Honda" },
  { id: "vw", name: "Volkswagen" },
  { id: "skoda", name: "Skoda" },
  { id: "bmw", name: "BMW" },
  { id: "mercedes", name: "Mercedes-Benz" },
  { id: "audi", name: "Audi" },
  { id: "renault", name: "Renault" },
  { id: "nissan", name: "Nissan" },
  { id: "jeep", name: "Jeep" },
  { id: "citroen", name: "Citroën" },
  { id: "byd", name: "BYD" },
  { id: "volvo", name: "Volvo" },
  { id: "lexus", name: "Lexus" },
  { id: "land-rover", name: "Land Rover" },
  { id: "jaguar", name: "Jaguar" },
  { id: "porsche", name: "Porsche" },
  { id: "mini", name: "MINI" },
  { id: "force", name: "Force Motors" },
  { id: "isuzu", name: "Isuzu" },
];

const RAW_INDIA_BRAND_MODELS: Omit<BrandModelOption, "variants">[] = [
  ...models("maruti", [
    ["swift", "Swift", "₹6.5L–9.5L"],
    ["baleno", "Baleno", "₹6.7L–10.0L"],
    ["dzire", "Dzire", "₹6.8L–10.0L"],
    ["wagonr", "Wagon R", "₹5.5L–7.5L"],
    ["brezza", "Brezza", "₹8.3L–14.0L"],
    ["ertiga", "Ertiga", "₹8.8L–13.5L"],
    ["grand-vitara", "Grand Vitara", "₹10.8L–20.0L"],
    ["fronx", "Fronx", "₹7.5L–13.0L"],
    ["invicto", "Invicto", "₹25.0L–31.0L"],
    ["jimny", "Jimny", "₹12.7L–15.0L"],
    ["celerio", "Celerio", "₹5.4L–7.0L"],
    ["alto-k10", "Alto K10", "₹3.9L–5.5L"],
    ["s-presso", "S-Presso", "₹4.2L–6.3L"],
    ["eeco", "Eeco", "₹5.3L–6.8L"],
    ["xl6", "XL6", "₹11.5L–14.5L"],
  ]),
  ...models("hyundai", [
    ["creta", "Creta", "₹11.0L–20.0L"],
    ["venue", "Venue", "₹7.9L–14.5L"],
    ["exter", "Exter", "₹6.1L–10.5L"],
    ["verna", "Verna", "₹11.0L–17.5L"],
    ["alcazar", "Alcazar", "₹16.0L–21.5L"],
    ["i20", "i20", "₹7.0L–12.0L"],
    ["aura", "Aura", "₹6.5L–10.0L"],
    ["tucson", "Tucson", "₹27.0L–34.5L"],
    ["ioniq5", "Ioniq 5", "₹45.0L–46.0L"],
    ["kona-ev", "Kona Electric", "₹24.0L–25.0L"],
  ]),
  ...models("tata", [
    ["nexon", "Nexon", "₹8.0L–15.5L"],
    ["nexon-ev", "Nexon EV", "₹12.5L–17.3L"],
    ["punch", "Punch", "₹6.1L–10.5L"],
    ["punch-ev", "Punch EV", "₹10.0L–14.2L"],
    ["harrier", "Harrier", "₹15.0L–26.5L"],
    ["harrier-ev", "Harrier EV", "₹21.5L–30.2L"],
    ["safari", "Safari", "₹15.5L–27.0L"],
    ["sierra", "Sierra", "₹16.0L–24.0L"],
    ["curvv", "Curvv", "₹10.5L–20.0L"],
    ["curvv-ev", "Curvv EV", "₹17.5L–22.3L"],
    ["tiago", "Tiago", "₹5.0L–8.5L"],
    ["tiago-ev", "Tiago EV", "₹8.0L–12.0L"],
    ["tigor", "Tigor", "₹6.3L–9.5L"],
    ["tigor-ev", "Tigor EV", "₹12.5L–13.5L"],
    ["altroz", "Altroz", "₹6.7L–11.0L"],
  ]),
  ...models("mahindra", [
    ["xuv700", "XUV700", "₹14.0L–26.0L"],
    ["xuv3xo", "XUV 3XO", "₹7.5L–15.0L"],
    ["scorpio-n", "Scorpio N", "₹13.0L–24.0L"],
    ["scorpio-classic", "Scorpio Classic", "₹13.0L–17.0L"],
    ["thar", "Thar", "₹11.0L–17.0L"],
    ["thar-roxx", "Thar Roxx", "₹12.5L–17.5L"],
    ["bolero", "Bolero", "₹9.5L–11.5L"],
    ["bolero-neo", "Bolero Neo", "₹9.5L–12.0L"],
    ["xuv400-ev", "XUV400 EV", "₹15.5L–17.5L"],
    ["be-6", "BE 6", "₹19.0L–27.0L"],
  ]),
  ...models("kia", [
    ["seltos", "Seltos", "₹11.0L–20.5L"],
    ["sonet", "Sonet", "₹7.8L–15.5L"],
    ["carens", "Carens", "₹10.5L–20.0L"],
    ["syros", "Syros", "₹9.0L–14.5L"],
    ["ev6", "EV6", "₹61.0L–66.0L"],
    ["ev9", "EV9", "₹1.05Cr–1.20Cr"],
  ]),
  ...models("toyota", [
    ["innova-crysta", "Innova Crysta", "₹19.5L–27.0L"],
    ["innova-hycross", "Innova Hycross", "₹19.0L–31.0L"],
    ["fortuner", "Fortuner", "₹33.5L–52.0L"],
    ["urban-cruiser-hyryder", "Urban Cruiser Hyryder", "₹11.0L–20.5L"],
    ["urban-cruiser-taisor", "Urban Cruiser Taisor", "₹7.7L–13.5L"],
    ["rumion", "Rumion", "₹10.5L–14.0L"],
    ["glanza", "Glanza", "₹6.8L–10.0L"],
    ["camry", "Camry", "₹48.0L–50.0L"],
    ["vellfire", "Vellfire", "₹1.22Cr–1.30Cr"],
    ["land-cruiser", "Land Cruiser 300", "₹2.31Cr+"],
  ]),
  ...models("mg", [
    ["hector", "Hector", "₹15.0L–22.0L"],
    ["hector-plus", "Hector Plus", "₹17.0L–23.0L"],
    ["astor", "Astor", "₹10.0L–19.0L"],
    ["gloster", "Gloster", "₹32.0L–43.0L"],
    ["comet-ev", "Comet EV", "₹7.0L–9.5L"],
    ["zs-ev", "ZS EV", "₹18.0L–26.0L"],
    ["windsor-ev", "Windsor EV", "₹14.0L–17.0L"],
  ]),
  ...models("honda", [
    ["city", "City", "₹12.0L–18.5L"],
    ["amaze", "Amaze", "₹7.5L–11.0L"],
    ["elevate", "Elevate", "₹11.5L–18.5L"],
    ["city-hybrid", "City Hybrid", "₹19.5L–21.0L"],
  ]),
  ...models("vw", [
    ["virtus", "Virtus", "₹11.5L–19.5L"],
    ["taigun", "Taigun", "₹11.5L–20.5L"],
    ["tiguan", "Tiguan", "₹35.0L–38.0L"],
    ["id4", "ID.4", "₹52.0L+"],
  ]),
  ...models("skoda", [
    ["kushaq", "Kushaq", "₹11.5L–20.0L"],
    ["slavia", "Slavia", "₹11.5L–19.5L"],
    ["kodiaq", "Kodiaq", "₹40.0L–45.0L"],
    ["octavia", "Octavia", "₹28.0L–32.0L"],
    ["superb", "Superb", "₹35.0L–40.0L"],
  ]),
  ...models("bmw", [
    ["2-series", "2 Series Gran Coupe", "₹43.0L–48.0L"],
    ["3-series", "3 Series", "₹55.0L–65.0L"],
    ["5-series", "5 Series", "₹72.0L–78.0L"],
    ["x1", "X1", "₹49.0L–53.0L"],
    ["x3", "X3", "₹68.0L–72.0L"],
    ["x5", "X5", "₹95.0L–1.05Cr"],
    ["x7", "X7", "₹1.27Cr–1.45Cr"],
    ["i4", "i4", "₹72.0L–78.0L"],
    ["i7", "i7", "₹1.95Cr+"],
    ["ix", "iX", "₹1.40Cr+"],
  ]),
  ...models("mercedes", [
    ["a-class-limousine", "A-Class Limousine", "₹42.0L–48.0L"],
    ["c-class", "C-Class", "₹57.0L–65.0L"],
    ["e-class", "E-Class", "₹78.0L–95.0L"],
    ["s-class", "S-Class", "₹1.55Cr–2.20Cr"],
    ["gla", "GLA", "₹48.0L–54.0L"],
    ["glb", "GLB", "₹52.0L–58.0L"],
    ["glc", "GLC", "₹73.0L–78.0L"],
    ["gle", "GLE", "₹1.05Cr–1.20Cr"],
    ["gls", "GLS", "₹1.30Cr–1.45Cr"],
    ["eqs", "EQS", "₹1.55Cr+"],
    ["eqb", "EQB", "₹77.0L–82.0L"],
  ]),
  ...models("audi", [
    ["a4", "A4", "₹45.0L–50.0L"],
    ["a6", "A6", "₹65.0L–72.0L"],
    ["q3", "Q3", "₹44.0L–50.0L"],
    ["q5", "Q5", "₹68.0L–75.0L"],
    ["q7", "Q7", "₹88.0L–1.05Cr"],
    ["q8", "Q8", "₹1.15Cr–1.25Cr"],
    ["e-tron-gt", "e-tron GT", "₹1.70Cr+"],
    ["q8-e-tron", "Q8 e-tron", "₹1.15Cr–1.30Cr"],
  ]),
  ...models("renault", [
    ["kiger", "Kiger", "₹6.1L–11.0L"],
    ["triber", "Triber", "₹6.0L–9.0L"],
    ["kwid", "Kwid", "₹4.7L–7.0L"],
    ["duster", "Duster", "₹10.0L–14.0L"],
  ]),
  ...models("nissan", [
    ["magnite", "Magnite", "₹6.0L–11.5L"],
    ["kicks", "Kicks", "₹10.0L–16.5L"],
    ["x-trail", "X-Trail", "₹40.0L+"],
  ]),
  ...models("jeep", [
    ["compass", "Compass", "₹19.0L–32.0L"],
    ["meridian", "Meridian", "₹33.0L–38.0L"],
    ["wrangler", "Wrangler", "₹67.0L–72.0L"],
    ["grand-cherokee", "Grand Cherokee", "₹77.0L+"],
  ]),
  ...models("citroen", [
    ["c3", "C3", "₹6.2L–9.5L"],
    ["c3-aircross", "C3 Aircross", "₹9.5L–14.0L"],
    ["ec3", "ë-C3", "₹12.0L–13.5L"],
    ["basalt", "Basalt", "₹8.0L–14.5L"],
  ]),
  ...models("byd", [
    ["atto-3", "Atto 3", "₹24.0L–28.0L"],
    ["seal", "Seal", "₹41.0L–53.0L"],
    ["e6", "e6", "₹29.0L–32.0L"],
  ]),
  ...models("volvo", [
    ["xc40", "XC40", "₹46.0L–48.0L"],
    ["xc60", "XC60", "₹68.0L–72.0L"],
    ["xc90", "XC90", "₹1.00Cr–1.15Cr"],
    ["s60", "S60", "₹46.0L–50.0L"],
    ["c40-recharge", "C40 Recharge", "₹62.0L–66.0L"],
  ]),
  ...models("lexus", [
    ["es", "ES", "₹62.0L–68.0L"],
    ["nx", "NX", "₹68.0L–72.0L"],
    ["rx", "RX", "₹1.05Cr–1.15Cr"],
    ["lx", "LX", "₹2.80Cr+"],
    ["lm", "LM", "₹2.30Cr+"],
  ]),
  ...models("land-rover", [
    ["defender", "Defender", "₹98.0L–2.40Cr"],
    ["discovery", "Discovery", "₹1.20Cr–1.45Cr"],
    ["discovery-sport", "Discovery Sport", "₹68.0L–75.0L"],
    ["range-rover-velar", "Range Rover Velar", "₹88.0L–1.05Cr"],
    ["range-rover-sport", "Range Rover Sport", "₹1.20Cr–1.80Cr"],
    ["range-rover", "Range Rover", "₹2.40Cr+"],
  ]),
  ...models("jaguar", [
    ["f-pace", "F-PACE", "₹72.0L–78.0L"],
    ["i-pace", "I-PACE", "₹1.05Cr+"],
    ["f-type", "F-TYPE", "₹97.0L+"],
  ]),
  ...models("porsche", [
    ["macan", "Macan", "₹88.0L–95.0L"],
    ["cayenne", "Cayenne", "₹1.30Cr–1.80Cr"],
    ["panamera", "Panamera", "₹1.45Cr–2.00Cr"],
    ["911", "911", "₹1.85Cr+"],
    ["taycan", "Taycan", "₹1.55Cr+"],
  ]),
  ...models("mini", [
    ["cooper-3-door", "Cooper 3-Door", "₹42.0L–45.0L"],
    ["cooper-s-3-door", "Cooper S 3-Door", "₹45.0L–48.0L"],
    ["countryman", "Countryman", "₹48.0L–52.0L"],
  ]),
  ...models("force", [
    ["gurkha", "Gurkha", "₹16.0L–18.0L"],
    ["trax-cruiser", "Trax Cruiser", "₹14.0L–16.0L"],
    ["urbania", "Urbania", "₹28.0L–35.0L"],
  ]),
  ...models("isuzu", [
    ["d-max-v-cross", "D-Max V-Cross", "₹22.0L–26.0L"],
    ["mu-x", "mu-X", "₹35.0L–38.0L"],
    ["s-cab-z", "S-CAB Z", "₹10.0L–12.0L"],
  ]),
];

export const INDIA_BRAND_MODELS: BrandModelOption[] = RAW_INDIA_BRAND_MODELS.map(withVariants);
